---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multitenancy-management.example.com
  resources:
  - tenantinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multitenancy-management.example.com
  resources:
  - tenantinfoes/finalizers
  verbs:
  - update
- apiGroups:
  - multitenancy-management.example.com
  resources:
  - tenantinfoes/status
  verbs:
  - get
  - patch
  - update
